using System.Text;
using System.Text.RegularExpressions;
using Microsoft.VisualBasic.FileIO;

namespace ArcFingerprint.Core;

public sealed record MappedRecipient(string ArcId, string Name, string Email, string FileName, string CopySha256, string CreatedUtc);

public static class RecipientMapping
{
    public const string DefaultFileName = "PRIVATE-recipient-mapping.csv";

    public static MappedRecipient? Find(string path, string arcId)
    {
        if (new FileInfo(path).Length > 2_000_000) throw new InvalidDataException("Mapping CSV exceeds 2 MB.");
        using var parser = new TextFieldParser(path, Encoding.UTF8, true) { HasFieldsEnclosedInQuotes = true, TrimWhiteSpace = true };
        parser.SetDelimiters(",");
        try
        {
            var headers = parser.ReadFields() ?? throw new InvalidDataException("The mapping CSV is empty.");
            if (headers.Distinct(StringComparer.OrdinalIgnoreCase).Count() != headers.Length)
                throw new InvalidDataException("The mapping CSV has duplicate column headers.");
            int Column(string name) => Array.FindIndex(headers, h => h.Equals(name, StringComparison.OrdinalIgnoreCase));
            int id = Column("ArcId"), name = Column("Name"), email = Column("Email"), file = Column("FileName"), hash = Column("CopySha256"), created = Column("CreatedUtc");
            if (id < 0 || name < 0 || email < 0 || file < 0)
                throw new InvalidDataException("Choose a PRIVATE-recipient-mapping.csv generated by the app. It needs ArcId, Name, Email, and FileName columns; a reader import list is not a mapping.");
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            MappedRecipient? match = null;
            int count = 0;
            while (!parser.EndOfData)
            {
                var row = parser.ReadFields()!;
                if (++count > 1000) throw new InvalidDataException("Mapping CSV exceeds 1,000 recipients.");
                if (row.Length != headers.Length) throw new InvalidDataException($"Mapping row {count + 1} has the wrong number of fields.");
                if (!Regex.IsMatch(row[id], "\\AARC-[0-9A-Fa-f]{32}\\z", RegexOptions.IgnoreCase))
                    throw new InvalidDataException($"Mapping row {count + 1} has an invalid ARC ID.");
                if (!seen.Add(row[id])) throw new InvalidDataException("This mapping contains duplicate ARC IDs. No recipient can be identified reliably until the duplicates are corrected.");
                if (new[] { row[name], row[email], row[file] }.Any(v => string.IsNullOrWhiteSpace(v) || v.Length > 512 || v.Any(char.IsControl)))
                    throw new InvalidDataException($"Mapping row {count + 1} has missing or invalid recipient details.");
                var copyHash = hash < 0 ? "" : row[hash];
                if (copyHash.Length > 0 && !Regex.IsMatch(copyHash, "\\A[0-9A-Fa-f]{64}\\z"))
                    throw new InvalidDataException($"Mapping row {count + 1} has an invalid copy hash.");
                if (row[id].Equals(arcId, StringComparison.OrdinalIgnoreCase))
                    match = new(row[id], row[name], row[email], row[file], copyHash, created < 0 ? "" : row[created]);
            }
            // Read the entire file before accepting a match, so later duplicate IDs cannot be missed.
            return match;
        }
        catch (MalformedLineException ex) { throw new InvalidDataException("The mapping CSV has malformed quoting or rows.", ex); }
    }
}

